name: pycomplex
channels:
  - anaconda
  - conda-forge
dependencies:
  - python
  - python.app
  - numpy
  - scipy
  - numpy-indexed
  - matplotlib
  - pycosat
  - cached-property
  - pytest
  - snakeviz
  - fastcache
  - funcsigs
