name: pycomplex
channels:
  - anaconda
  - conda-forge
dependencies:
  - python # >= 3.8 got to relax for pydy
#  - python.app    # [osx]
  - numpy
  - scipy
  - numpy-indexed
  - matplotlib
  - pycosat
  - cached-property
  - pytest
  - fastcache
  - funcsigs
  - pip:
    - git+https://github.com/eelcohoogendoorn/numga.git
#  - pyamg
#  - vispy
#  - scikit-image
#  - pandas
#  - sympy
