name: pycomplex
channels:
  - anaconda
  - conda-forge
dependencies:
  - python # >= 3.8 got to relax for pydy
  - python.app    # [osx]
  - numpy
  - scipy
  - numpy-indexed
  - matplotlib
  - pycosat
  - cached-property
  - pytest
#  - snakeviz
  - fastcache
  - funcsigs
#  - pyamg
#  - vispy
#  - scikit-image
#  - shapely
#  - opencv
#  - pyserial
#  - pandas
  - sympy
#  - control # for bike controller
#  - pydy
#  - cython