package:
  name: pycomplex
  version: "0.1.0"

about:
  home: https://github.com/EelcoHoogendoorn/pycomplex
  license: Freely Distributable
  summary: Library for working with simplicial and cubical complexes

source:
  path: ..

requirements:
  build:
  - python
  - setuptools
  run:
  - python
  - numpy
  - scipy
  - numpy-indexed
  - matplotlib
  - pycosat
  - cached-property
  - fastcache
  - funcsigs

build:
  number: 0
  noarch: python

test:
  source_files:
  - conftest.py
  requires:
  - pytest
  imports:
  - pycomplex
  commands:
  - pytest --pyargs pycomplex
