about:
  home: https://github.com/EelcoHoogendoorn/pycomplex
  license: Freely Distributable
  summary: Library for working with simplicial and cubical complexes
source:
  path: ..

package:
  name: pycomplex
  version: 0.0.2
requirements:
  build:
  - python
  - setuptools
  run:
  - python
  - numpy
  - scipy
  - numpy-indexed
  - matplotlib
  - pycosat
  - cached-property
  - fastcache

build:
  number: 1
  script: python setup.py install
  noarch: python

test:
#  commands:
#  - py.test --pyargs pycomplex
  imports:
  - pycomplex
#  requires:
#  - pytest
