about:
  home: https://github.com/EelcoHoogendoorn/pycomplex
  license: Freely Distributable
  summary: Library for working with simplicial and cubical complexes
source:
  path: ..

package:
  name: pycomplex
  version: 0.1.0
requirements:
  build:
  - python
  - setuptools
  run:
  - python
  - numpy
  - scipy
  - numpy-indexed
  - matplotlib
  - pycosat
  - cached-property
  - fastcache
  - funcsigs

build:
  number: 1
  noarch: python

test:
  requires:
  - pytest
  imports:
  - pycomplex
  commands:
  - pytest --pyargs pycomplex --show_plot=False
